name: CI – Automação Web

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'   # ajuste se necessário

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Chrome for Selenium
      run: |
        sudo apt update
        sudo apt install -y chromium-browser chromium-chromedriver
        sudo ln -s /usr/bin/chromium-browser /usr/bin/google-chrome
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Run Robot Framework tests
      run: |
        mkdir -p results
        robot --outputdir results test_case/

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: rf-test-results
        path: results/
